#!/bin/bash
echo
echo 'Self Extracting Installer'
echo

VERSION='v3.1'
# Set up the Vyatta environment
source /opt/vyatta/etc/functions/script-template
shopt -s expand_aliases
alias show='_vyatta_op_run show'
alias run='/opt/vyatta/bin/vyatta-op-cmd-wrapper'
alias check='/bin/cli-shell-api'

atexit () {
	tput cnorm
}
trap atexit exit ${?}

DMASQ_MSG="
cache-size 2048
listen-on eth0 # LAN Interface
listen-on eth2 # LAN Interface
listen-on lo
name-server 208.67.220.220
name-server 208.67.222.222
name-server 2620:0:ccc::2
name-server 2620:0:ccd::2
options bogus-priv
options domain=ubnt.home # Set to match your chosen home domain
options except-interface=eth1 # Don't listen on the WAN Interface
options expand-hosts
options listen-address=127.0.0.1
options localise-queries
options strict-order
system

"

install_menu () {
	local IFS=' '
	local PS3='Enter option number and hit return => '
	local OPTIONS=('INSTALL' 'REMOVE' 'TEST' 'BACKUP' 'PURGE' 'QUIT')
	shopt -s checkwinsize
	local COLUMNS=$(tput cols)

while true;
do
	echo -ne "Would you like to INSTALL, REMOVE, TEST or BACKUP dnsmasq blacklist functionality (if previously installed)?\n\nRun PURGE to clean up stale config sessions.\n\n" | fold -s -w ${COLUMNS}
	select CHOICE in ${OPTIONS[@]}; do
		case ${REPLY} in
			1)		clear console
					check existsActive service dns forwarding
					if [[ $? == 0 ]]
					then
					./setup
					sudo ./blacklist.t
					break
					else
						tput setaf 1
						echo 'CANNOT PROCEED: [service dns forwarding] must be configured first!'
						tput setaf 7
						echo 'Sample dns forwarding (dnsmasq) configuration:'
						tput setaf 3
						echo -ne ${DMASQ_MSG}
						tput setaf 7
					fi
					return 1
					;;
			2)		clear console
					if /opt/vyatta/bin/yesno -n 'Do you want to completely remove Blacklist? [y/N]: '
					then
						./remove
						break
					fi
					;;
			3)		clear console
					sudo ./blacklist.t
					break
					;;
			4)		check existsActive service dns forwarding blacklist
					if [[ $? == 0 ]]
					then
						RESULT=$(run show configuration commands | grep blacklist > /config/user-data/blacklist.cmds)
						tput setaf 2
						echo -ne "\ndnsmasq blacklist configuration backed up to /config/user-data/blacklist.cmds\n\n"
						tput setaf 7
						echo -ne "To restore, run:\n\tconfigure\n\tsource /config/user-data/blacklist.cmds\n\tcommit\n\tsave\n\texit\n\n" | fold -s -w ${COLUMNS}
					else
						tput setaf 1
						echo -ne "\ndnsmasq blacklist isn't configured, nothing to backup!\n\n"
						tput setaf 7
					fi
					break
					;;
			5)		clear console
					sudo ./ubnt-cln-cfg-orphans.sh
					break
					;;
			6|*)	return 0
					;;
		esac
	done
done
}

CDIR="$(pwd)"

# Make sure script runs as root
if [[ ${EUID} -eq 0 ]]; then
	echo 'This script must be run as the ubnt admin user, not root!'
	exit 1
fi

export TMPDIR=$(mktemp -d /tmp/selfextract.XXXXXX)

ARCHIVE=$(awk '/^__ARCHIVE_BELOW__/ {print NR + 1; exit 0; }' $0)

tail -n+${ARCHIVE} $0 | tar xz -C "${TMPDIR}"

cd "${TMPDIR}"

install_menu

cd "${CDIR}"
rm -rf "${TMPDIR}"

exit 0

__ARCHIVE_BELOW__
