#!/usr/bin/env bash
export COPY_EXTENDED_ATTRIBUTES_DISABLE=true
export COPYFILE_DISABLE=true

DROPBOX="/Users/Neil/Dropbox/EdgeMax"
ADBLOCK="ADBLOCK"
INSTALL="install_adblock"

if [[ -e "${0##*/}" ]]; then
	BASEDIR="$(pwd)"
	[[ -f ${ADBLOCK}setup.tgz ]] && rm ${ADBLOCK}setup.tgz
	cd payload
	tar zcf ../payload.tgz --exclude='._*' --exclude='.svn' --exclude='.DS_Store' --exclude='*.bak' --exclude='*~' ./*
	cd ..

	if [ -e "payload.tgz" ]; then
		cat decompress payload.tgz > ${INSTALL}
	else
		echo "payload.tgz does not exist"
		exit 1
	fi

	chmod 755 ${INSTALL}
	tar zcf ${INSTALL}.tgz ${INSTALL} 
	echo "${INSTALL} created"
	[[ -d "${DROPBOX}/" ]] && install -m 0755 ${INSTALL}.tgz "${DROPBOX}/" 
	cd ..
	tar -zcf ${ADBLOCK}setup.tgz --exclude='._*' --exclude='.svn' --exclude='.DS_Store' --exclude='*.bak' --exclude='*~' "${BASEDIR}"/*
	mv ${ADBLOCK}setup.tgz "${BASEDIR}"/
	cd "${BASEDIR}"
	[[ ${1} ]] && /usr/bin/scp "${BASEDIR}"/${INSTALL} ${1}@scratch:/tmp/ersetup
else
	echo "$(basename $0) must be run in the directory where it is located."
fi
exit 0
