#!/bin/bash
echo
echo "Self Extracting Installer"
echo

install_menu () {
	local IFS=' '
	local PS3="Enter option number and hit return => "
	local OPTIONS="INSTALL REMOVE QUIT"
	shopt -s checkwinsize
	local COLUMNS=$(tput cols)

	echo "Would you like to install or remove dnsmasq blacklist functionality (if previously installed)?" | fold -s -w ${COLUMNS}

	while true; do
		select CHOICE in ${OPTIONS}; do
			case ${REPLY} in
				1)		./setup
						return $?
						;;
				2)		if /opt/vyatta/bin/yesno -n 'Do you want to completely remove Blacklist? [y/N]: '
						then
							./remove
						fi
						return $?
						;;
				3|*)	return 0
				;;
			esac
		done
	done
}

CDIR="$(pwd)"

# Make sure script runs as root
if [[ ${EUID} -ne 0 ]]; then
	echo "This script must be run as root, use: sudo ${CDIR}/ersetup" #1>&2
	exit 1
fi

export TMPDIR=`mktemp -d /tmp/selfextract.XXXXXX`

ARCHIVE=`awk '/^__ARCHIVE_BELOW__/ {print NR + 1; exit 0; }' $0`

tail -n+${ARCHIVE} $0 | tar xz -C "${TMPDIR}"

cd "${TMPDIR}"

install_menu

cd "${CDIR}"
rm -rf "${TMPDIR}"

exit 0

__ARCHIVE_BELOW__
