#!/usr/bin/env bash
export COPY_EXTENDED_ATTRIBUTES_DISABLE=true
export COPYFILE_DISABLE=true

RFC2136_Installer=rfc2136_install

if [ -e "${0##*/}" ]; then
	BASEDIR=`pwd`
	rm $RFC2136_Installer.tgz
	cd payload
	tar zcf ../payload.tgz --exclude='._*' --exclude='.svn' --exclude='.DS_Store' --exclude='*.bak' --exclude='*~' ./*
	cd ..

	if [ -e "payload.tgz" ]; then
		cat decompress payload.tgz > $RFC2136_Installer.tgz
	else
		echo "payload.tgz does not exist"
		exit 1
	fi

	chmod 755 $RFC2136_Installer.tgz
	echo "$RFC2136_Installer.tgz created"
	cd ..
	tar -zcf $RFC2136_Installer.tgz --exclude='._*' --exclude='.svn' --exclude='.DS_Store' --exclude='*.bak' --exclude='*~' $BASEDIR/*
	mv $RFC2136_Installer.tgz ${BASEDIR}/
	cd ${BASEDIR}
	[ ${1} ] && /usr/bin/scp ${BASEDIR}/$RFC2136_Installer.tgz  ${1}@scratch:/tmp/
else
	echo "$(basename $0) must be run in the directory where it is located."
fi
exit 0
