#!/usr/bin/perl -T

use strict;

# use warnings;
use IO::Socket::INET;

my $crlf  = "\015\012";
my $pixel = pack( "C*",
    qw(71 73 70 56 57 97 1 0 1 0 128 0 0 255 255 255 0 0 0 33 249 4 1 0 0 0 0 44 0 0 0 0 1 0 1 0 0 2 2 68 1 0 59)
);

my $sock = new IO::Socket::INET(
    LocalHost => $ARGV[0],
    LocalPort => $ARGV[1],
    Proto     => 'tcp',
    Listen    => 30,
    Reuse     => 1
) or die "Error: cannot bind to socket: $@ exit\n";

while ( my $new_sock = $sock->accept() ) {
    while (<$new_sock>) {
        chop;
        chop;
        if ( $_ eq '' ) { last; }
    }
    print $new_sock "HTTP/1.1 200 OK$crlf";
    print $new_sock "Content-type: image/gif$crlf";
    print $new_sock "Accept-ranges: bytes$crlf";
    print $new_sock "Content-length: 43$crlf$crlf";
    print $new_sock $pixel;
    shutdown( $new_sock, 2 );
    undef($new_sock);
}

close($sock);
exit(0);
