#!/usr/bin/env bash
# **** License ****
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# A copy of the GNU General Public License is available as
# '/usr/share/common-licenses/GPL' in the Debian GNU/Linux distribution
# or on the World Wide Web at `http://www.gnu.org/copyleft/gpl.html'.
# You can also obtain it by writing to the Free Software Foundation,
# Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,
# MA 02110-1301, USA.
#
# Author: Neil Beadle
# Date: September 2015
#
# **** End License ****
# Remove dnsmasq ADBLOCK and blacklist blocking from an EdgeMax router
# Use at your own risk
#

VERSION="v2.0"

# Uncomment for debugging or syntax checking
# set -x
# Syntax check - uncomment for non execution dry run:
# set -n

# Make sure script runs as root
if [[ ${EUID} != 0 ]]
then
	echo "This script must be run as root, use: [sudo $(pwd)/ersetup]"
	exit 1
fi

# Set up the Vyatta environment
source /opt/vyatta/etc/functions/script-template
OPRUN=/opt/vyatta/bin/vyatta-op-cmd-wrapper
CFGRUN=/opt/vyatta/sbin/vyatta-cfg-cmd-wrapper
API=/bin/cli-shell-api
shopt -s expand_aliases

alias begin='${CFGRUN} begin'
alias commit='${CFGRUN} commit'
alias copy='${CFGRUN} copy'
alias delete='${CFGRUN} delete'
alias discard='${CFGRUN} discard'
alias end='${CFGRUN} end'
alias save='${CFGRUN} save'
alias set='${CFGRUN} set'
alias version='${OPRUN} show version'

SHOWVER=$(version | sed 's/$/;/g')
BUILD=$(echo ${SHOWVER} | awk 'BEGIN {RS=";"} /Build ID:/ {print $3}')
VER=$(echo ${SHOWVER} | awk 'BEGIN {RS=";"} /Version:/ {print $2}')
ME="${0##*/} ${VERSION}: "
ERROR=0

# Make sure we clean up session on deliberate and accidental exits
atexit ()
{
	end
}

# Install adblock and bogon support
delete_adblock_support ()
{
	SCRIPTS="/config/scripts"
	ADBLOCK="update-blacklists-dnsmasq.pl"
	CFGDIR="/opt/vyatta/share/vyatta-cfg/templates/service/dns/forwarding/blacklist/"
	NODEDEF="node.def"
	ERROR=0

	echo "Removing ${ADBLOCK} from ${SCRIPTS}/"
	rm -f "${SCRIPTS}/${ADBLOCK}" || ERROR=1

	echo "help: Add and delete blacklist blackhole IP, exclusions and URL sources" > "${CFGDIR}/${NODEDEF}"

	echo "Opening EdgeMax configuration session..."
	begin || ERROR=1

	echo "Removing ADBLOCK blacklist and task scheduler entry for ${ADBLOCK}..."
	delete service dns forwarding blacklist || ERROR=1
	delete system task-scheduler task update_blacklists  || ERROR=1

	echo "Committing configuration..."
	commit || ERROR=1

	echo "Saving configuration..."
	save || ERROR=1

	echo "Ending configuration session..."
	end || ERROR=1

	echo "Removing blacklist configuration templates for ${ADBLOCK}..."

	rm -rf "${CFGDIR}/"
	return ${ERROR}
}

# This is where we run the script using the above functions
trap atexit exit ${?}

if /opt/vyatta/bin/yesno -y 'Do you want to completely remove ADBLOCK? '
then
	if delete_adblock_support
	then
		echo 'ADBLOCK has been completely removed.'
		exit 0
	else
		echo 'There were problems removing ADBLOCK'
		exit 1
	fi
fi