#!/bin/bash
#echo ""
#echo "Self Extracting Installer"
#echo ""
CDIR=$(pwd)
# Make sure script runs as root
if [[ ${EUID} -ne 0 ]]; then
	echo "This script must be run as root, use: sudo ${CDIR}/ersetup" #1>&2
	exit 1
fi

export TMPDIR=`mktemp -d /tmp/selfextract.XXXXXX`

ARCHIVE=`awk '/^__ARCHIVE_BELOW__/ {print NR + 1; exit 0; }' $0`

tail -n+${ARCHIVE} $0 | tar xz -C ${TMPDIR}

cd ${TMPDIR}

./installer ${CDIR}

cd ${CDIR}
rm -rf ${TMPDIR}

exit 0

__ARCHIVE_BELOW__
